[project]
name = "wet-net-streamlit-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.50.0",
    "wet_net",
]

[tool.uv.sources]
wet_net = { workspace = true }